### ISSUE TITLE
Allow "testName" field to list only the tests that are specific to the selected "product"

### ISSUE THREAD

**Issue by mcharanrm** [cloud-bulldozer/cpt-dashboard#99]
Hello Team, I am from PSAP team, a team within the Perf&Scale group. In the CPT dashboard, for a selected product, I see that, "Test name" filter basically list all the test names that are available in the system but ideally it should only list the tests that are specific to the product. This basically causes lot of ambiguity among users who are just trying to see the KPI jobs that are available for one product, say "RED HAT INSIGHTS".

**Comment by jtaleric** [comment]
You are asking for the filters to update based on user selections, right? 

cc @chentex
